language: ruby
arch:
  - amd64
  - ppc64le
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head
  - jruby-1.7.26
  - jruby-9.1.17.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: ruby-head
      arch: ppc64le
    - rvm: jruby-head
      arch: ppc64le
before_install:
  - gem update bundler
